version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
      # - bootstrap.memory_lock=true
      # - ELASTICSEARCH_USERNAME=root
      # - ELASTIC_PASSWORD=root
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
       - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  elasticsearch-data-volume:
    driver: local